version: 0.2

env:
  secrets-manager:
    username: arn:aws:secretsmanager:us-west-2:483351323773:secret:dev/Appdata/letlock/postgres-wjeh8F:username
    password: arn:aws:secretsmanager:us-west-2:483351323773:secret:dev/Appdata/letlock/postgres-wjeh8F:password
    host: arn:aws:secretsmanager:us-west-2:483351323773:secret:dev/Appdata/letlock/postgres-wjeh8F:host
    port: arn:aws:secretsmanager:us-west-2:483351323773:secret:dev/Appdata/letlock/postgres-wjeh8F:port
    databasename: arn:aws:secretsmanager:us-west-2:483351323773:secret:dev/Appdata/letlock/postgres-wjeh8:databasename
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`      
      - mvn clean install -Dspring.profiles.active="dev"
  post_build:
    commands:
      - echo Build completed on `date`
      - mv target/letlock-filetransfer-backend-0.0.1-SNAPSHOT.jar  application.jar
artifacts:
  files:
    - application.jar