version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install -Dspring.profiles.active="dev"
  post_build:
    commands:
      - mv target/letlock-filetransfer-backend-0.0.1-SNAPSHOT.jar letlockbackend.jar
      - echo Build completed on `date`
artifacts:
  files:
    - letlockbackend.jar
    - .ebextensions/**/*