version: 0.2

env:
  secrets-manager:
    dev/Appdata/letlock/postgres:username
    dev/Appdata/letlock/postgres:password
    edev/Appdata/letlock/postgres:engine
    dev/Appdata/letlock/postgres:host
    dev/Appdata/letlock/postgres:port
    dev/Appdata/letlock/postgres:databasename
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`      
      - mvn clean install -Dspring.profiles.active="dev"
  post_build:
    commands:
      - echo Build completed on `date`
      - mv target/letlock-filetransfer-backend-0.0.1-SNAPSHOT.jar  application.jar
artifacts:
  files:
    - application.jar